- name: Copy Systemd unit to the system path
  copy:
    src="{{ custom_tor_systemd_unit }}"
    dest="{{ custom_tor_systemd_unit_remote_path }}"
    remote_src=True
  become: yes

- name: Remove hardening section from the Systemd unit
  lineinfile:
    regexp: "^[(Private)|(Protect)|(Read)|(Capability)].*$"
    dest: "{{ custom_tor_systemd_unit_remote_path }}"
    state: absent

- name: Set Systemd unit type
  replace:
    dest: "{{ custom_tor_systemd_unit_remote_path }}"
    regexp: "^Type=.*$"
    replace: "Type=simple"

- name: Activate Systemd unit
  systemd:
    name: tor
    enabled: yes
    user: yes
