---
- name: Install apt dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ custom_tor_apt_dependencies }}"
  become: yes

- name: Install role apt dependencies
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ custom_tor_role_apt_dependencies }}"
  become: yes

