- name: Copy Systemd unit to the system path
  copy:
    src="{{ custom_tor_systemd_unit }}"
    dest="{{ custom_tor_systemd_units_path }}"
    remote_src=True
  become: yes

- name: Activate Systemd unit
  systemd:
    name: tor
    enabled: yes
  become: yes
