---
- stat: path="{{ dest_dir }}/autogen.sh"
  register: autogen_sh

- name: Autogen custom Tor if autogen.sh exists (i.e. git clone).
  command: ./autogen.sh chdir="{{ dest_dir }}"
  when: autogen_sh.stat.exists

- name: Configure custom Tor.
  command: ./configure --disable-asciidoc chdir="{{ dest_dir }}"

- name: Make custom Tor
  make: chdir="{{ dest_dir }}"
  
- name: Install custom Tor
  make:
    target: install
    chdir: "{{ dest_dir }}"
  become: yes
